// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class Location
    {
        public Location()
        {
            VisitorTransactions = new HashSet<VisitorTransaction>();
            Registers = new HashSet<VisitorRegistration>();
        }

        public int Id { get; set; }
        public string LocationName { get; set; }
        public string LocationDescription { get; set; }
        public string LocationAddress { get; set; }
        public string LocationEmail { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public DateTime? UpdateDateTime { get; set; }

        public virtual ICollection<VisitorTransaction> VisitorTransactions { get; set; }

        public virtual ICollection<VisitorRegistration> Registers { get; set; }
    }
}