// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class PasswordSetting
    {
        public int Id { get; set; }
        public int? MaxPwdLife { get; set; }
        public int? MaxPwdFailedCount { get; set; }
        public int? MinPwdLength { get; set; }
        public int? MinLowerCase { get; set; }
        public int? MinUpperCase { get; set; }
        public int? MinNumeric { get; set; }
        public int? MinSpecialCharacter { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}