// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class VisitorIdentity
    {
        public VisitorIdentity()
        {
            VisitorRegistrations = new HashSet<VisitorRegistration>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public string CreateBy { get; set; }
        public DateTime CreatedDateTime { get; set; }

        public virtual ICollection<VisitorRegistration> VisitorRegistrations { get; set; }
    }
}