// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class VisitorTransaction
    {
        public long Id { get; set; }
        public long VisitorRegistrationId { get; set; }
        public DateTime? TransactionDateTime { get; set; }
        public int? TransactionType { get; set; }
        public string Door { get; set; }
        public int? LocationId { get; set; }
        public DateTime? EntryDateTime { get; set; }
        public DateTime? ExitDateTime { get; set; }
        public int? TerminalId { get; set; }

        public virtual Location Location { get; set; }
        public virtual VisitorRegistration VisitorRegistration { get; set; }
    }
}