// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class TokenAuth
    {
        public int Id { get; set; }
        public string UserKey { get; set; }
        public string UserCode { get; set; }
        public string Token { get; set; }
        public DateTime? TokenRequestDateTime { get; set; }
        public DateTime? TokenExpiryDateTime { get; set; }
        public string PasswordHash { get; set; }
    }
}