// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class UnitDetail
    {
        public int Id { get; set; }
        public int? LocationId { get; set; }
        public string BlockNo { get; set; }
        public string UnitNo { get; set; }
        public string UnitId { get; set; }
    }
}