// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class UsersSessionsTracking
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string Status { get; set; }
        public DateTime? LoginDateTime { get; set; }
        public DateTime? LogoutDateTime { get; set; }
        public DateTime? AttemptedDateTime { get; set; }
        public string Remarks { get; set; }
    }
}