// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class VisitorRegistration
    {
        public VisitorRegistration()
        {
            CardIssueDetails = new HashSet<CardIssueDetail>();
            VisitorTransactions = new HashSet<VisitorTransaction>();
            Locations = new HashSet<Location>();
        }

        public long Id { get; set; }
        public string VisitorName { get; set; }
        public int? IdType { get; set; }
        public string NricOrPassport { get; set; }
        public string VisitorContanctNo { get; set; }
        public string Email { get; set; }
        public string VisitorVisitDesc { get; set; }
        public string BlockNo { get; set; }
        public string UnitNo { get; set; }
        public string CompanyName { get; set; }
        public int VisitTypeId { get; set; }
        public long? TerminalId { get; set; }
        public int VisitorStatus { get; set; }
        public string VehicleNo { get; set; }
        public int? PurposeOfVisitId { get; set; }
        public DateTime? VistStartDateTime { get; set; }
        public DateTime? VistEndDateTime { get; set; }
        public bool IsBlockListed { get; set; }
        public string CreateBy { get; set; }
        public DateTime CreateDateTime { get; set; }
        public bool? IsDeleted { get; set; }
        public string UpdateBy { get; set; }
        public DateTime? UpdateDateTime { get; set; }
        public string ReasonForBlacklist { get; set; }
        public int? UploadtoController { get; set; }
        public string BlacklistBy { get; set; }
        public DateTime? BlacklistDateTime { get; set; }
        public string RegistrationBy { get; set; }
        public int? ManualCheckIn { get; set; }
        public string ManualCheckInBy { get; set; }
        public bool IsEnabled { get; set; }
        public bool PushOverStayer { get; set; }
        public bool EnabledOverStayer { get; set; }
        public bool PushVisitors { get; set; }
        public bool OverStayer { get; set; }
        public bool IsDisabled { get; set; }
        public virtual VisitorIdentity IdTypeNavigation { get; set; }
        public virtual VisitPurpose PurposeOfVisit { get; set; }
        public virtual VisitType VisitType { get; set; }
        public virtual ICollection<CardIssueDetail> CardIssueDetails { get; set; }
        public virtual ICollection<VisitorTransaction> VisitorTransactions { get; set; }

        public virtual ICollection<Location> Locations { get; set; }
    }
}