// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class AssetType
    {
        public AssetType()
        {
            Assets = new HashSet<Asset>();
        }

        public int Id { get; set; }
        public string DeviceTypeName { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<Asset> Assets { get; set; }
    }
}