// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class BlacklistTransaction
    {
        public long Id { get; set; }
        public string NricOrPassport { get; set; }
        public string BlacklistBy { get; set; }
        public DateTime? BlacklistDateTime { get; set; }
        public string BlacklistReason { get; set; }
        public bool? IsBlacklisted { get; set; }
        public string BlacklistResult { get; set; }
    }
}