// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class CardIssueDetail
    {
        public long Id { get; set; }
        public string CardNumber { get; set; }
        public DateTime? IssueDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsPushed { get; set; }
        public DateTime? CreateDateTime { get; set; }
        public string NricOrPassport { get; set; }

        public virtual VisitorRegistration NricOrPassportNavigation { get; set; }
    }
}