// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class Status
    {
        public int Id { get; set; }
        public string StatusName { get; set; }
        public bool? IsDeleted { get; set; }
    }
}