// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATTSystems.SFA.Model.DBModel
{
    public partial class VisitType
    {
        public VisitType()
        {
            VisitorRegistrations = new HashSet<VisitorRegistration>();
        }

        public int Id { get; set; }
        public string VisitTypeName { get; set; }
        public string Description { get; set; }
        public string CreateBy { get; set; }
        public DateTime CreateDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string Chinese { get; set; }
        public string Melayu { get; set; }

        public virtual ICollection<VisitorRegistration> VisitorRegistrations { get; set; }
    }
}